### ISSUE TITLE
Fails with a regular expression error in older browsers

### ISSUE THREAD

**Issue by sheremet-va** [markedjs/marked#2430]
**Marked version:** 4.0.12

**Describe the bug**
- Fails with an error `invalid identity escape in regular expression` on older browsers (Firefox <= 72)

<img width="848" alt="Снимок экрана 2022-03-30 в 14 15 14" src="https://user-images.githubusercontent.com/16173870/160822235-9ae755ec-4704-45cf-ac1e-1459d2c2d458.png">

**To Reproduce**

**Expected behavior**

**Comment by UziTech** [comment]
This is already fixed in the `umd` and `min` builds. If you have to support browsers that old you should use those builds.

**Comment by DmitryKashinskyAtSpark** [comment]
@UziTech I've faced that same issue in the current versions of the Firefox and Chrome browsers. The `marked` is imported into react application and bundled using default `react-scripts build` (CRA) setup. Is it an app specific bundling issue or the issue might still exist in the library itself?

Console output:
```
Uncaught SyntaxError: Invalid regular expression: /^ {0,3}({1,6} ").replace("|lheading","").replace("|table","").replace("blockquote"," {0,3}>").replace("fences"," {0,3}(?:`{3,}(?=[^`\\n]*\\n)|~{3,})[^\\n]*\\n").replace("list"," {0,3}(?:[*+-]|1[.)]) ").replace("html","</: Nothing to repeat (at main.1ae637cf.js:2:460437)
```

**Comment by UziTech** [comment]
That seems like a bundling issue.

**Comment by DmitryKashinskyAtSpark** [comment]
@UziTech Thanks for reply! Yep, figured out that it was due to one of the deployment steps where we replace tokenized strings in produced bundled files. Somehow tokens matched with that regexps and corrupted the file.

So sorry for disturbing and great job here on `marked`!

**Comment by nsbarsukov** [comment]
> This is already fixed in the `umd` and `min` builds. If you have to support browsers that old you should use those builds.

@UziTech Hello!
I've faced with the same issue. I use `marked.min.js`-build .

**package.json:**
```json
"marked": "^4.2.12"
```

Firefox 70 throws this error `SyntaxError: invalid identity escape in regular expression`

**Comment by nsbarsukov** [comment]
@UziTech there are two ways to reproduce problem:

### 1) Use already deployed application
Open https://taiga-ui.dev/next in old Firefox (for example, 70)

### 2) Debug locally
1. Clone https://github.com/Tinkoff/taiga-ui
2. Checkout to `main`-branch
3. Run `npm ci`
4. Run `npm start`
5. Open `http://localhost:3333` in Firefox (for example, 65)

https://user-images.githubusercontent.com/35179038/215762555-27d5b6d9-70b5-4f8c-9bbf-91419a98f08a.mov

The error points to this code line:
<img width="910" alt="error" src="https://user-images.githubusercontent.com/35179038/215762810-d22fc6f2-1686-4ad9-8c8c-dd1e5118bf59.png">

**Comment by UziTech** [comment]
@nsbarsukov those are Unicode property escapes. They work in Firefox 78+. If you need to support older browsers you can use older versions of marked.

**Comment by UziTech** [comment]
Alternatively you could transpile marked with babel and whatever babel plugins will change that regex to not use unicode property escapes. The problem is that the resulting regex will be massive so we won't support browsers that old.

**Comment by nsbarsukov** [comment]
@UziTech thanks for you quick response!
It is sad to hear it :(

To use v1 version of your lib I need to downgrade `ngx-markdown`-dep (it uses `marked` inside) to v10.
But `ngx-markdown@10` [requires only the 10th Angular](https://github.com/jfcere/ngx-markdown/blob/v10.1.1/lib/package.json#L36-L38) (we have Angular 12).
Downgrading Angular is not an option.
Unfortunately, we should find new library alternative :(

___
btw:

I think, the section [Compatibility](https://github.com/markedjs/marked#compatibility) should be updated.
> Browser: Not IE11 :)

It is not true for the latest version of lib :(

**Comment by nsbarsukov** [comment]
@UziTech we use your library inside [Taiga UI](https://github.com/Tinkoff/taiga-ui).

We have to support older versions of browsers because this UI KIT is used inside 50+ projects in production. 
https://taiga-ui.dev/browser-support

Our analytics say that we can't reject some old Firefox versions for a while (there are users which is still use these versions).

**Comment by nsbarsukov** [comment]
Fortunatelly, `ngx-markdown@10` (it uses `marked@1.1.0` inside) works with Angular 12.

As workaround, we will downgrade the library.

@UziTech Thanks for your help!
